const API_BASE=(window.APP_CONFIG?.API_BASE||"https://buzzer-divtelegram-one-api.onrender.com").replace(/\/$/,"");
const $=id=>document.getElementById(id);
const state={slot:1,groups:[],selected:new Set(),activeJob:null,jobPoll:null,slots:JSON.parse(localStorage.getItem("bdto_slots")||"{}")};
for(let i=1;i<=5;i++) if(!state.slots[i]) state.slots[i]={phone:"",apiId:"",apiHash:"",loggedIn:false};
function saveSlots(){localStorage.setItem("bdto_slots",JSON.stringify(state.slots));}
function log(msg,type=""){const d=document.createElement("div");d.className=`log-line ${type}`;d.textContent=`[${new Date().toLocaleTimeString("id-ID")}] ${msg}`;$("logBox").prepend(d);}
function notice(msg,type=""){const n=$("authNotice");n.textContent=msg;n.className=`notice ${type}`;}
async function api(path,options={}){const r=await fetch(`${API_BASE}${path}`,{headers:{"Content-Type":"application/json",...(options.headers||{})},...options});let data={};try{data=await r.json()}catch{}if(!r.ok)throw new Error(data.error||`HTTP ${r.status}`);return data;}
function slotObj(){return state.slots[state.slot];}
function renderSlots(){const sel=$("slotSelect");sel.innerHTML="";for(let i=1;i<=5;i++){const o=document.createElement("option");o.value=i;o.textContent=`Akun ${i}`;sel.appendChild(o)}sel.value=state.slot;$("slotStatus").innerHTML=[1,2,3,4,5].map(i=>`<span class="${state.slots[i].loggedIn?'on':''}">▪ Akun ${i}: ${state.slots[i].loggedIn?'AKTIF':'NONAKTIF'}</span>`).join("");const active=slotObj();$("activeAccountText").textContent=active.loggedIn?`Akun aktif: Akun ${state.slot} terhubung`:`Akun aktif: belum login`;const total=Object.values(state.slots).filter(s=>s.loggedIn).length;$("summary").textContent=total?`Status koneksi: ${total} akun terhubung · ${state.groups.length} grup dimuat`:`Status koneksi: belum ada akun terhubung`;}
function loadSlotInputs(){const s=slotObj();$("apiId").value=s.apiId||"";$("apiHash").value=s.apiHash||"";$("phone").value=s.phone||"";$("otp").value="";$("password2fa").value="";$("otpRow").classList.add("hidden");$("twoFaRow").classList.add("hidden");notice("");state.groups=[];state.selected.clear();renderGroups();renderSlots();if(s.loggedIn&&s.phone) refreshGroups(true);}
function persistInputs(){Object.assign(slotObj(),{apiId:$("apiId").value.trim(),apiHash:$("apiHash").value.trim(),phone:$("phone").value.trim()});saveSlots();}
function renderGroups(){const q=$("groupSearch").value.toLowerCase();const only=$("selectedOnly").checked;const list=$("groupList");const rows=state.groups.filter(g=>(!q||g.title.toLowerCase().includes(q))&&(!only||state.selected.has(g.id)));$("groupCount").textContent=`${state.groups.length} grup`;if(!rows.length){list.innerHTML=`<div class="empty">${state.groups.length?'Tidak ada grup sesuai filter.':'Belum ada grup yang dimuat.'}</div>`;return}list.innerHTML="";rows.forEach(g=>{const row=document.createElement("label");row.className="group-item";const c=document.createElement("input");c.type="checkbox";c.checked=state.selected.has(g.id);c.onchange=()=>{c.checked?state.selected.add(g.id):state.selected.delete(g.id);renderSlots()};const span=document.createElement("span");span.textContent=g.title;row.append(c,span);list.appendChild(row)});renderSlots();}
async function checkStatus(slot=slotObj()){if(!slot.phone)return false;try{const d=await api(`/auth/status?phone=${encodeURIComponent(slot.phone)}`);slot.loggedIn=!!d.loggedIn;saveSlots();return slot.loggedIn}catch{return false}}
async function refreshGroups(silent=false){const s=slotObj();if(!s.phone){if(!silent)notice("Nomor Telegram pada slot ini belum diisi.","error");return}const btn=$("refreshGroupsBtn");btn.disabled=true;if(!silent)notice("Memuat grup asli dari akun Telegram...");try{const d=await api(`/groups?phone=${encodeURIComponent(s.phone)}`);state.groups=Array.isArray(d.groups)?d.groups:[];state.selected.clear();s.loggedIn=true;saveSlots();renderGroups();notice(`Berhasil sinkron ${state.groups.length} grup dari Akun ${state.slot}.`,"success");log(`Sinkron grup Akun ${state.slot}: ${state.groups.length} grup.`,"success")}catch(e){s.loggedIn=false;saveSlots();state.groups=[];renderGroups();notice(e.message,"error");log(`Gagal sinkron grup: ${e.message}`,"error")}finally{btn.disabled=false;renderSlots()}}
$("slotSelect").onchange=e=>{persistInputs();state.slot=Number(e.target.value);loadSlotInputs()};["apiId","apiHash","phone"].forEach(id=>$(id).addEventListener("change",persistInputs));
$("loginBtn").onclick=async()=>{persistInputs();const s=slotObj();notice("Meminta kode Telegram...");$("loginBtn").disabled=true;try{const d=await api("/auth/send-code",{method:"POST",body:JSON.stringify({apiId:s.apiId,apiHash:s.apiHash,phone:s.phone})});$("otpRow").classList.remove("hidden");$("twoFaRow").classList.add("hidden");notice(d.message||"Kode OTP dikirim.","success");log(`OTP diminta untuk Akun ${state.slot}.`)}catch(e){notice(e.message,"error");log(e.message,"error")}finally{$("loginBtn").disabled=false}};
$("verifyOtpBtn").onclick=async()=>{const s=slotObj();notice("Memverifikasi OTP...");try{const d=await api("/auth/verify-code",{method:"POST",body:JSON.stringify({phone:s.phone,code:$("otp").value.trim()})});if(d.needsPassword){$("twoFaRow").classList.remove("hidden");notice(d.message||"Masukkan password 2FA.","success");log("OTP benar. Password 2FA diperlukan.")}else if(d.loggedIn){s.loggedIn=true;saveSlots();notice("Login berhasil. Memuat grup...","success");renderSlots();await refreshGroups(true)}}catch(e){notice(e.message,"error");log(e.message,"error")}};
$("verify2faBtn").onclick=async()=>{const s=slotObj();notice("Memverifikasi password 2FA...");try{const d=await api("/auth/password",{method:"POST",body:JSON.stringify({phone:s.phone,password:$("password2fa").value})});if(d.loggedIn){s.loggedIn=true;saveSlots();$("twoFaRow").classList.add("hidden");notice("2FA berhasil. Memuat grup asli...","success");renderSlots();await refreshGroups(true)}}catch(e){notice(e.message,"error");log(e.message,"error")}};
$("logoutBtn").onclick=async()=>{const s=slotObj();if(!s.phone)return notice("Slot ini belum memiliki nomor Telegram.","error");if(!confirm(`Logout Akun ${state.slot} dan hapus sesi backend?`))return;try{await api("/auth/logout",{method:"POST",body:JSON.stringify({phone:s.phone})});s.loggedIn=false;saveSlots();state.groups=[];state.selected.clear();renderGroups();renderSlots();notice("Logout berhasil.","success");log(`Akun ${state.slot} logout.`)}catch(e){notice(e.message,"error")}};
$("refreshGroupsBtn").onclick=()=>refreshGroups(false);$("selectAllBtn").onclick=()=>{state.groups.forEach(g=>state.selected.add(g.id));renderGroups()};$("clearBtn").onclick=()=>{state.selected.clear();renderGroups()};$("groupSearch").oninput=renderGroups;$("selectedOnly").onchange=renderGroups;
const templates=()=>JSON.parse(localStorage.getItem("bdto_templates")||"{}");function renderTemplates(){const t=templates(),s=$("templateSelect");s.innerHTML='<option value="">Template tersimpan</option>'+Object.keys(t).map(k=>`<option>${k}</option>`).join("")}$("saveTemplateBtn").onclick=()=>{const name=$("templateName").value.trim();if(!name)return log("Isi nama template terlebih dahulu.","error");const t=templates();t[name]=$("message").value;localStorage.setItem("bdto_templates",JSON.stringify(t));renderTemplates();log(`Template "${name}" disimpan.`,"success")};$("loadTemplateBtn").onclick=()=>{const t=templates(),n=$("templateSelect").value;if(n&&t[n]!=null){$("message").value=t[n];log(`Template "${n}" dimuat.`)}};
function readLinks(){const links=[];for(let i=1;i<=3;i++){const label=$(`linkLabel${i}`).value.trim();const url=$(`linkUrl${i}`).value.trim();if(!label&&!url)continue;if(!label||!url)throw new Error(`Link ${i}: nama dan URL harus diisi lengkap.`);let parsed;try{parsed=new URL(url)}catch{throw new Error(`Link ${i}: URL tidak valid.`)}if(!["http:","https:"].includes(parsed.protocol))throw new Error(`Link ${i}: hanya URL http/https yang didukung.`);links.push({label,url:parsed.toString()})}return links}
function setLinks(links=[]){for(let i=1;i<=3;i++){const item=links[i-1]||{};$(`linkLabel${i}`).value=item.label||"";$(`linkUrl${i}`).value=item.url||""}}
$("clearLinksBtn").onclick=()=>{setLinks([]);log("Link CTA dikosongkan.")};
const campaigns=()=>JSON.parse(localStorage.getItem("bdto_campaigns")||"{}");function renderCampaigns(){const c=campaigns(),s=$("campaignSelect");s.innerHTML='<option value="">Pilih kampanye</option>'+Object.keys(c).map(k=>`<option>${k}</option>`).join("")}$("saveCampaignBtn").onclick=()=>{const n=$("campaignName").value.trim();if(!n)return log("Isi nama kampanye.","error");let links=[];try{links=readLinks()}catch(e){return log(e.message,"error")}const c=campaigns();c[n]={message:$("message").value,delay:$("delay").value,maxGroups:$("maxGroups").value,links};localStorage.setItem("bdto_campaigns",JSON.stringify(c));renderCampaigns();log(`Kampanye "${n}" disimpan.`,"success")};$("loadCampaignBtn").onclick=()=>{const c=campaigns(),n=$("campaignSelect").value;if(n&&c[n]){$("message").value=c[n].message||"";$("delay").value=c[n].delay||10;$("maxGroups").value=c[n].maxGroups||20;setLinks(c[n].links||[]);log(`Kampanye "${n}" dimuat.`)}};
$("imageInput").onchange=e=>{$("imageName").textContent=e.target.files?.[0]?.name||"Tidak ada gambar dipilih"};$("backupBtn").onclick=()=>{const data={templates:templates(),campaigns:campaigns()};const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}));a.download="buzzer-divtelegram-backup.json";a.click();URL.revokeObjectURL(a.href)};$("restoreInput").onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());if(data.templates)localStorage.setItem("bdto_templates",JSON.stringify(data.templates));if(data.campaigns)localStorage.setItem("bdto_campaigns",JSON.stringify(data.campaigns));renderTemplates();renderCampaigns();log("Backup berhasil direstore.","success")}catch{log("File restore tidak valid.","error")}};
$("testBtn").onclick=async()=>{try{const d=await api("/health");log(`Backend aktif. Akun aktif di server: ${d.activeAccounts??'-'}.`,"success")}catch(e){log(`Backend tidak terhubung: ${e.message}`,"error")}};

async function selectedPayload(includeSchedule=false){
  const s=slotObj();
  if(!s.phone||!s.loggedIn) throw new Error(`Akun ${state.slot} belum login.`);
  const groupIds=[...state.selected];
  if(!groupIds.length) throw new Error("Pilih minimal 1 grup tujuan.");
  const message=$("message").value;
  const f=$("imageInput").files?.[0]||null;
  let media=null;
  if(f){
    if(f.size>10*1024*1024) throw new Error("Media maksimal 10 MB.");
    media={name:f.name,mime:f.type||"application/octet-stream",data:await fileToDataUrl(f)};
  }
  const links=readLinks();
  const payload={phone:s.phone,groupIds,message,media,links,delaySeconds:Number($("delay").value||1),maxGroups:Number($("maxGroups").value||20)};
  if(includeSchedule){
    const raw=$("scheduleAt").value;
    if(!raw) throw new Error("Pilih tanggal dan jam schedule.");
    payload.scheduleAt=new Date(raw).toISOString();
  }
  return payload;
}
function fileToDataUrl(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(new Error("Gagal membaca media."));r.readAsDataURL(file)})}
function updateSummaryJob(job){
  if(!job)return;
  $("summary").textContent=`Status koneksi: Akun ${state.slot} ${slotObj().loggedIn?'terhubung':'belum login'} • Batch ${job.status}: ${job.sent}/${job.total} terkirim • ${job.failed} gagal`;
}
async function pollJob(id){
  clearInterval(state.jobPoll);
  const tick=async()=>{try{const d=await api(`/send/jobs/${encodeURIComponent(id)}`);const j=d.job;state.activeJob=j;updateSummaryJob(j);if(j.current)log(`Proses: ${j.current} (${j.sent+j.failed}/${j.total})`);if(["done","failed","stopped"].includes(j.status)){clearInterval(state.jobPoll);state.jobPoll=null;log(`Batch selesai: ${j.sent} terkirim, ${j.failed} gagal. Status ${j.status}.`,j.failed?"error":"success");for(const r of (j.results||[]).filter(x=>!x.ok))log(`${r.title||r.groupId}: ${r.error}`,"error")}}catch(e){clearInterval(state.jobPoll);state.jobPoll=null;log(`Gagal membaca status batch: ${e.message}`,"error")}};
  await tick();state.jobPoll=setInterval(tick,1500);
}
$("startBtn").onclick=async()=>{try{if(state.jobPoll)throw new Error("Masih ada batch kirim yang dipantau.");const payload=await selectedPayload(false);log(`Memulai kirim ke ${Math.min(payload.groupIds.length,payload.maxGroups)} grup...`);const d=await api("/send/start",{method:"POST",body:JSON.stringify(payload)});state.activeJob=d.job;log(`Batch dimulai. Job ${d.job.id}.`,"success");pollJob(d.job.id)}catch(e){log(e.message,"error")}};
$("stopBtn").onclick=async()=>{try{if(!state.activeJob?.id)return log("Tidak ada batch aktif.");const d=await api(`/send/jobs/${encodeURIComponent(state.activeJob.id)}/stop`,{method:"POST",body:"{}"});state.activeJob=d.job;log("Permintaan Stop dikirim. Pesan yang sudah terkirim tidak ditarik kembali.")}catch(e){log(e.message,"error")}};
$("scheduleBtn").onclick=async()=>{try{const payload=await selectedPayload(true);const when=new Date(payload.scheduleAt);log(`Mengirim jadwal ke Telegram untuk ${Math.min(payload.groupIds.length,payload.maxGroups)} grup...`);const d=await api("/schedule",{method:"POST",body:JSON.stringify(payload)});log(`Schedule tersimpan di Telegram: ${d.scheduled} berhasil, ${d.failed} gagal. Mulai ${when.toLocaleString("id-ID")}.`,d.failed?"error":"success");for(const r of (d.results||[]).filter(x=>!x.ok))log(`${r.title||r.groupId}: ${r.error}`,"error")}catch(e){log(e.message,"error")}};
$("exportLogBtn").onclick=()=>{const text=[...document.querySelectorAll(".log-line")].reverse().map(x=>x.textContent).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text],{type:"text/plain"}));a.download="buzzer-divtelegram-log.txt";a.click();URL.revokeObjectURL(a.href)};
renderTemplates();renderCampaigns();renderSlots();loadSlotInputs();(async()=>{for(let i=1;i<=5;i++)if(state.slots[i].phone)await checkStatus(state.slots[i]);renderSlots();})();
